app/Models/Page.php
<?php

/*
 * This file is part of Hifone.
 *
 * (c) Hifone.com <hifone@hifone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hifone\Models;

use AltThree\Validator\ValidatingTrait;
use Illuminate\Database\Eloquent\Model;
use Venturecraft\Revisionable\RevisionableTrait;

class Page extends Model
{
    use ValidatingTrait, RevisionableTrait;

    /**
     * The fillable properties.
     *
     * @var string[]
     */
    protected $fillable = [
        'title',
        'slug',
        'body',
        'body_original',
        'created_at',
        'updated_at',
    ];

    /**
     * The validation rules.
     *
     * @var string[]
     */
    public $rules = [
        'title'      => 'required|string',
        'slug'       => 'required|string',
        'body'       => 'string',
    ];

    public function getUrlAttribute()
    {
        return ($this->slug) ? route('page', $this->slug) : '/?fr=page_error';
    }
}

app/Models/User.php
<?php

/*
 * This file is part of Hifone.
 *
 * (c) Hifone.com <hifone@hifone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hifone\Models;

use AltThree\Validator\ValidatingTrait;
use Hifone\Presenters\UserPresenter;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Model;
use McCool\LaravelAutoPresenter\HasPresenter;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, HasPresenter
{
    use Authenticatable, CanResetPassword, EntrustUserTrait, ValidatingTrait;

    // Enable hasRole( $name ), can( $permission ),
    //   and ability($roles, $permissions, $options)

    // Enable soft delete

    protected $dates = ['deleted_at'];

    /**
     * The properties that cannot be mass assigned.
     *
     * @var string[]
     */
    protected $guarded = ['id', 'notifications', 'is_banned'];

    /**
     * The hidden properties.
     *
     * These are excluded when we are serializing the model.
     *
     * @var string[]
     */
    protected $hidden = ['password', 'remember_token'];
    /**
     * The validation rules.
     *
     * @var string[]
     */
    public $rules = [
        'username' => ['required', 'max:15', 'regex:/\A[A-Za-z0-9\-\_\.]+\z/'],
        'email'    => 'required|max:255',
        'password' => 'required',
    ];

    protected $searchable = [
        'username',
    ];

    /**
     * Find by username, or throw an exception.
     *
     * @param string $username The username.
     * @param mixed  $columns  The columns to return.
     *
     * @throws ModelNotFoundException if no matching User exists.
     *
     * @return User
     */
    public static function findByUsernameOrFail(
        $username,
        $columns = ['*']
    ) {
        if (!is_null($user = static::whereUsername($username)->first($columns))) {
            return $user;
        }

        throw new ModelNotFoundException();
    }

    public function favoriteThreads()
    {
        return $this->belongsToMany(Thread::class, 'favorites')->withTimestamps();
    }

    /**
     * Users can have many threads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function threads()
    {
        return $this->hasMany(Thread::class);
    }

    /**
     * Users can have many replies.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    /**
     * Users can have many credits.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function credits()
    {
        return $this->hasMany(Credit::class);
    }

    public function notifications()
    {
        return $this->morphMany(Notification::class, 'object');
    }

    public function follows()
    {
        return $this->morphMany(Follow::class, 'followable');
    }

    public function identities()
    {
        return $this->hasMany(Identity::class);
    }

    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    public function scopeSearch($query, $search)
    {
        return  $query->where(function ($query) use ($search) {
            $query->where('username', 'LIKE', "%$search%");
        });
    }

    /**
     * ----------------------------------------
     * UserInterface
     * ----------------------------------------.
     */
    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    public function getAuthPassword()
    {
        return $this->password;
    }

    /**
     * ----------------------------------------
     * RemindableInterface
     * ----------------------------------------.
     */
    public function getReminderEmail()
    {
        return $this->email;
    }

    public function getRememberToken()
    {
        return $this->remember_token;
    }

    public function setRememberToken($value)
    {
        $this->remember_token = $value;
    }

    public function getRememberTokenName()
    {
        return 'remember_token';
    }

    public function getAvatarAttribute()
    {
        return $this->avatar_url ? $this->avatar_url : '/images/avatar.jpg';
    }

    public function getAvatarSmallAttribute()
    {
        return $this->avatar_url ? $this->avatar_url : '/images/avatar_small.jpg';
    }

    /**
     * Cache github avatar to local.
     */
    public function cacheAvatar()
    {
        //Download Image
        $guzzle = new GuzzleHttp\Client();
        $response = $guzzle->get($this->image_url);

        //Get ext
        $content_type = explode('/', $response->getHeader('Content-Type'));
        $ext = array_pop($content_type);

        $avatar_name = $this->id.'_'.time().'.'.$ext;
        $save_path = public_path('uploads/avatars/').$avatar_name;

        //Save File
        $content = $response->getBody()->getContents();
        file_put_contents($save_path, $content);

        //Delete old file
        if ($this->avatar) {
            @unlink(public_path('uploads/avatars/').$this->avatar);
        }

        //Save to database
        $this->avatar = $avatar_name;
        $this->save();
    }

    /**
     * Get the presenter class.
     *
     * @return string
     */
    public function getPresenterClass()
    {
        return UserPresenter::class;
    }
}

app/Http/Controllers/UserController.php
<?php

/*
 * This file is part of Hifone.
 *
 * (c) Hifone.com <hifone@hifone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hifone\Http\Controllers;

use AltThree\Validator\ValidationException;
use Auth;
use Hash;
use Hifone\Models\Identity;
use Hifone\Models\Location;
use Hifone\Models\Provider;
use Hifone\Models\Reply;
use Hifone\Models\Thread;
use Hifone\Models\User;
use Illuminate\Support\Facades\View;
use Input;
use Intervention\Image\ImageManagerStatic as Image;
use Redirect;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['edit', 'update', 'destroy', 'unbind']]);
    }

    public function index()
    {
        $users = User::recent()->take(48)->get();

        return $this->view('users.index')
            ->withUsers($users);
    }

    public function show(User $user)
    {
        $threads = Thread::forUser($user->id)->recent()->limit(10)->get();
        $replies = Reply::forUser($user->id)->recent()->limit(10)->get();

        return $this->view('users.show')
            ->withUser($user)
            ->withThreads($threads)
            ->withReplies($replies);
    }

    public function showByUsername($username)
    {
        return $this->show(User::findByUsernameOrFail($username));
    }

    public function edit(User $user)
    {
        $this->needAuthorOrAdminPermission($user->id);
        $providers = Provider::recent()->get();
        $ids = $user->identities()->pluck('provider_id')->all();

        return $this->view('users.edit')
            ->withProviders($providers)
            ->withTab(Input::get('tab'))
            ->withBindOauthIds($ids)
            ->withUser($user);
    }

    public function update(User $user)
    {
        $this->needAuthorOrAdminPermission($user->id);
        $data = Input::only('nickname', 'location', 'company', 'website', 'signature', 'bio', 'locale');

        try {
            if ($data['location']) {
                $location = Location::where('name', $data['location'])->first();
                if (!is_null($location)) {
                    $data['location_id'] = $location->id;
                }
            }

            $user->update($data);
        } catch (ValidationException $e) {
            return Redirect::route('user.edit')
                ->withInput(Input::all())
                ->withErrors($e->getMessageBag());
        }

        return Redirect::route('user.edit', $user->id)
            ->withSuccess(sprintf('%s %s', trans('hifone.awesome'), trans('hifone.success')));
    }

    public function destroy(User $user)
    {
        $this->needAuthorOrAdminPermission($user->id);
    }

    public function replies(User $user)
    {
        $replies = Reply::forUser($user->id)->recent()->paginate(15);

        return $this->view('users.replies')
            ->withUser($user)
            ->withReplies($replies);
    }

    public function threads(User $user)
    {
        $threads = Thread::forUser($user->id)->recent()->paginate(15);

        return $this->view('users.threads')
            ->withUser($user)
            ->withThreads($threads);
    }

    public function favorites(User $user)
    {
        $threads = $user->favoriteThreads()->paginate(15);

        return $this->view('users.favorites')
            ->withUser($user)
            ->withThreads($threads);
    }

    public function credits(User $user)
    {
        $credits = $user->credits()->paginate(15);

        return $this->view('users.credits')
            ->withUser($user)
            ->withCredits($credits);
    }

    public function city($name)
    {
        $location = Location::where('name', $name)->firstOrFail();
        $users = $location->users()->paginate(15);

        return $this->view('users.city')
            ->withLocation($location)
            ->withUsers($users);
    }

    public function blocking(User $user)
    {
        $user->is_banned = (!$user->is_banned);
        $user->save();

        return Redirect::route('users.show', $user->id);
    }

    public function unbind(User $user)
    {
        $this->needAuthorOrAdminPermission($user->id);
        $record = Identity::where('user_id', '=', $user->id)->where('provider_id', '=', Input::get('provider_id'))->first();

        $record ? $record->delete() : null;

        return Redirect::route('user.edit', $user->id)
            ->withSuccess(trans('hifone.login.oauth.unbound_success'));
    }

    public function avatarupdate()
    {
        $user_id = Auth::id();
        $originFile = Input::file('avatar');

        $path = ($user_id % 10).'/'.($user_id % 10).'/';
        $destinationPath = public_path().'/uploads/avatar/'.$path;
        $saveName = $user_id.'.jpg';

        $originFile->move($destinationPath, $saveName);
        $img = Image::make($destinationPath.'/'.$saveName);

        $img->resize(192, 192)
            ->encode('jpg')
            ->save();

        $img->resize(48, 48)
            ->encode('jpg')
            ->save($destinationPath.$user_id.'_small.jpg');

        $user = Auth::user();
        $user->avatar_url = '/uploads/avatar/'.$path.$user_id.'.jpg';
        $user->save();

        return Redirect::back()
            ->withSuccess(trans('hifone.users.avatar_upload_success'));
    }

    protected function resetPassword()
    {
        $user = Auth::user();

        if (Hash::check(Input::only('old_password')['old_password'], $user->password)) {
            $password = Input::only('password')['password'];

            $password_confirmation = Input::only('password_confirmation')['password_confirmation'];

            if (!($password == $password_confirmation)) {
                return Redirect::back()
                    ->withInfo('当前输入新密码与错密码不一致, 请重新输入.');
            } else {
                $user->password = Hash::make(Input::only('password')['password']);

                $user->save();

                return Redirect::back()
                    ->withSuccess('密码修改成功!');
            }
        } else {
            return Redirect::back()
                ->withError('输入当前密码输入错误, 请重新输入.');
        }
    }
}

resources/views/users/city.blade.php
@extends('layouts.default')

@section('title')
{{ trans('hifone.users.info') }}_@parent
@stop

@section('content')
 <div id="users" class="box">
    <div id="hot_users" class="panel panel-default user-list">
        <div class="panel-heading">{{ $location->name }} {{ trans('hifone.member') }}</div>
        <div class="panel-body row">
            @foreach($users as $user)
            <div class="user col-sm-1">
                <div class="avatar">
                    <a href="{{ route('user.home', $user->username) }}"><img class="media-object avatar-48" src="{{ $user->avatar }}"></a>
                </div>
                <div class="name"><a href="{{ route('user.home', $user->username) }}">{{ $user->username }}</a></div>
            </div>
            @endforeach
        </div>
        <div class="panel-footer clearfix">
            {!! $users->appends(Request::except('page', '_pjax'))->render() !!}
        </div>
    </div>
</div>
@stop

resources/views/users/credits.blade.php
@extends('layouts.default')

@section('title')
{{{ $user->username }}} {{ trans('hifone.threads.list') }}_@parent
@stop

@section('content')

<div class="users-show">

  <div class="col-md-3 box">
    @include('users.partials.basicinfo')
  </div>

  <div class="col-md-9 left-col">


  <div class="panel panel-default">


    <div class="panel-body">
      @include('users.partials.infonav')
      @if (count($credits))
        @include('users.partials.credits')
        <div class="pull-right add-padding-vertically">
            {{ $credits->render() }}
        </div>
      @else
        <div class="empty-block">{{ trans('hifone.credits.noitem') }}</div>
      @endif

    </div>

  </div>
</div>
</div>

@stop

resources/views/users/edit.blade.php
@extends('layouts.default')

@section('title')
{{ trans('hifone.users.edit_profile') }}@parent
@stop

@section('content')

<div class="users-show">

  <div class="col-md-3 box">
    @include('users.partials.basicinfo')
  </div>

  <div class="col-md-9 left-col">

    <div class="panel panel-default">

      <div class="panel-body ">
        <ul class="nav nav-tabs" role="tablist">
          <li @if(!$tab) class="active" @endif><a href="{{ route('user.edit',['id'=>$user->id]) }}">{{ trans('hifone.users.info') }}</a></li>
          <li @if($tab=='avatar') class="active" @endif><a href="{{ route('user.edit',['id'=>$user->id,'tab'=>'avatar']) }}">{{ trans('hifone.users.avatar') }}</a></li>
          <li @if($tab=='password') class="active" @endif><a href="{{ route('user.edit',['id'=>$user->id,'tab'=>'password']) }}">{{ trans('hifone.users.password') }}</a></li>
        </ul>
        @if($tab == 'avatar')
        <form class="form-horizontal" method="post" action="/settings/update-avatar" enctype="multipart/form-data" id="avatar-form">
                {{ csrf_field() }}
                <h5><i class="fa fa-image"></i>&nbsp;&nbsp;{{ trans('hifone.users.edit_avatar') }}</h5><hr>
                <div class="form-group">
                    <div class="col-sm-4 avatar-setting-container">
                       <img src="{{Auth::user()->avatar}}" id="avatar" class="upload-btn" style="cursor: pointer;">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4 status-post-submit">
                    <button type="button" class="btn btn-primary upload-btn">
                        {{ trans('hifone.users.upload_avatar') }}
                    </button>
                    <span class="loading"></span>
                    <input type="file" id="avatarinput" name="avatar" class="hide">
                    <span class="help-block">
                        {{ trans('hifone.users.upload_avatar_help') }}</span>
                    <button type="submit" class="btn btn-primary hidden" id="avatarinput-submit">更新</button>
                    </div>
                </div>
        </form>
        @elseif($tab == 'password')
        <form class="form-horizontal" method="post" action="/settings/resetPassword" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <h5><i class="fa fa-wrench"></i>&nbsp;&nbsp;{{ trans('hifone.users.password_settings') }}</h5><hr>
            <div class="form-group">
                <div class="col-sm-4">
                <input type="password" name="old_password" placeholder="{{ trans('hifone.users.password_current') }}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4">
                <input type="password" name="password" placeholder="{{ trans('hifone.users.password_new') }}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4">
                <input type="password" name="password_confirmation" placeholder="{{ trans('hifone.users.password_new_confirmation') }}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4 status-post-submit">
                <button type="submit" class="btn btn-primary" id="update-password">{{ trans('hifone.users.password_update') }}</button>
                </div>
            </div>
      </form>
      @else
      {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'patch']) !!}
          <h5><i class="fa fa-tasks"></i>&nbsp;&nbsp;{{ trans('hifone.users.info') }}</h5>
          <div class="form-group">
            {!! Form::text('nickname', null, ['class' => 'form-control', 'placeholder' => trans('hifone.users.nickname')]) !!}
          </div>
          <div class="form-group">
            {!! Form::text('location', null, ['class' => 'form-control', 'placeholder' => trans('hifone.users.location')]) !!}
            <div class="help-block">{{ trans('hifone.users.location_help') }}</div>
          </div>
          <div class="form-group">
            {!! Form::text('company', null, ['class' => 'form-control', 'placeholder' => trans('hifone.users.company')]) !!}
          </div>
          <div class="form-group">
            {!! Form::text('website', null, ['class' => 'form-control', 'placeholder' => trans('hifone.users.website')]) !!}
          </div>
          <div class="form-group">
            {!! Form::textarea('signature', null, ['class' => 'form-control',
                                              'rows' => 3,
                                              'placeholder' => trans('hifone.users.signature')]) !!}
          </div>
          <div class="form-group">
            {!! Form::textarea('bio', null, ['class' => 'form-control',
                                              'rows' => 3,
                                              'placeholder' => trans('hifone.users.bio')]) !!}
          </div>
          <div class="form-group">
              <label>{{ trans('hifone.users.locale') }}</label>
              <select name="locale" class="form-control" required>
                  <option value="">{{ trans('hifone.users.select_language') }}</option>
                  @foreach($langs as $key => $lang)
                      <option value="{{ $key }}" {{ $user->locale == $key ? "selected" : null }}>{{ $lang }}</option>
                  @endforeach
              </select>
          </div>
          <div class="form-group status-post-submit">
            {!! Form::submit(trans('forms.update'), ['class' => 'btn btn-primary', 'id' => 'user-edit-submit']) !!}
          </div>
        {!! Form::close() !!}
      @endif
      </div>
    </div>
  </div>


</div>

@stop

resources/views/users/favorites.blade.php
@extends('layouts.default')

@section('title')
{{{ $user->username }}} {{ trans('hifone.favorites.favorites') }}_@parent
@stop

@section('content')


<div class="users-show">

  <div class="col-md-3 box">
    @include('users.partials.basicinfo')
  </div>

<div class="col-md-9 left-col">


  <div class="panel panel-default">

    <div class="panel-body">
      @include('users.partials.infonav')
      @if (count($threads))
	      @include('users.partials.threads')
	      <div class="pull-right add-padding-vertically"> {{ $threads->render() }} </div>
      @else
        <div class="empty-block">{{ trans('hifone.favorites.noitem') }}</div>
      @endif

    </div>

  </div>
  </div>
</div>

@stop

resources/views/users/index.blade.php
@extends('layouts.default')

@section('title')
{{ trans('hifone.users.list') }}_@parent
@stop

@section('content')

<div class="panel panel-default users-index">

    <div class="panel-heading text-center">
        {{ trans('hifone.users.list') }} ( {{ trans('hifone.users.total') }} {{ $stats['user_count'] }} )
    </div>

    <div class="panel-body">
    @foreach ($users as $user)
        <div class="col-md-1 remove-padding-right">
            <div class="avatar">
              <a href="{{ route('user.show', $user->username) }}" class="users-index-{{ $user->id }}">
                <img src="{{ $user->avatar_small }}" class="img-thumbnail avatar"  style="width:48px;height:48px;margin-bottom: 20px;"/>
              </a>
            </div>
        </div>
    @endforeach
    </div>

</div>
@stop

resources/views/users/replies.blade.php
@extends('layouts.default')

@section('title')
{!! $user->username !!} {!! trans('hifone.replies.list') !!}_@parent
@stop

@section('content')


<div class="users-show">

  <div class="col-md-3 box">
    @include('users.partials.basicinfo')
  </div>

  <div class="col-md-9 left-col">


  <div class="panel panel-default">

    <div class="panel-body">
      @include('users.partials.infonav')
      @if (count($replies))
	      @include('users.partials.replies')
	      <div class="pull-right add-padding-vertically">
	        {!! $replies->render() !!}
	      </div>
      @else
	       <div class="empty-block">{!! trans('hifone.replies.noitem') !!}</div>
      @endif

    </div>

  </div>
</div>
</div>

@stop

resources/views/users/show.blade.php
@extends('layouts.default')

@section('title')
{{{ $user->username }}} {{ trans('hifone.users.info') }}_@parent
@stop

@section('content')

<div class="users-show">

  <div class="col-md-3 box">
    @include('users.partials.basicinfo')
  </div>

  <div class="col-md-9 left-col">

    @if ($user->is_banned)
      <div class="text-center alert alert-info"><b>{{ trans('hifone.users.is_banned') }}</b></div>
    @endif

    <div class="panel panel-default">
        <div class="panel-body">
          @include('users.partials.infonav')
        
            <div class="user-card">
                <div class="header">
                  <a class="avatar" href="{{ $user->url }}" target="_blank"><img src="{{ $user->avatar }}"><strong><span>{{ '@'.$user->username }}</span></strong></a>
                  @if($current_user && $current_user->id != $user->id)
                   @if (Auth::check() && $user->follows()->forUser(Auth::user()->id)->count())
                      <a class="button followable" data-type="User" data-id="{{ $user->id }}" data-url="{{ route('follow.user',$user->id) }}">
                          <i class="fa fa-minus"></i> {!! trans('hifone.unfollow') !!}
                      </a>
                    @else
                      <a class="button followable active" data-type="User" data-id="{{ $user->id }}" data-url="{{ route('follow.user',$user->id) }}">
                          <i class="fa fa-plus"></i> {!! trans('hifone.follow') !!}
                      </a>
                    @endif
                  @endif
                </div>
                <ul class="status">
                  <li><a href="{!! route('user.threads', $user->id) !!}"><strong>{{ $user->thread_count }}</strong>{{ trans('hifone.threads.threads') }}</a></li>
                  <li><a href="{!! route('user.replies', $user->id) !!}"><strong>{{ $user->reply_count }}</strong>{{ trans('hifone.replies.replies') }}</a></li>
                  <li><a href="#"><strong>0</strong>{{ trans('hifone.users.followers') }}</a></li>
                </ul>
                <div class="footer">
                {{ $user->bio }}
                </div>
        </div>
    </div>
  </div>
</div>
</div>
@stop

resources/views/users/threads.blade.php
@extends('layouts.default')

@section('title')
{{{ $user->username }}} {{ trans('hifone.threads.list') }}_@parent
@stop

@section('content')

<div class="users-show">

  <div class="col-md-3 box">
    @include('users.partials.basicinfo')
  </div>

  <div class="col-md-9 left-col">


  <div class="panel panel-default">


    <div class="panel-body">
      @include('users.partials.infonav')
      @if (count($threads))
	    @include('users.partials.threads')
	    <div class="pull-right add-padding-vertically">
	        {{ $threads->render() }}
	    </div>
      @else
        <div class="empty-block">{{ trans('hifone.threads.noitem') }}</div>
      @endif

    </div>

  </div>
</div>
</div>

@stop